Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib64/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/asyncio/run.py", line 186, in asyncio_worker
    app = load_application(config.application_path, config.wsgi_max_body_size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/utils.py", line 110, in load_application
    module = import_module(import_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1069, in get_code
  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib64/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/asyncio/run.py", line 186, in asyncio_worker
    app = load_application(config.application_path, config.wsgi_max_body_size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/utils.py", line 110, in load_application
    module = import_module(import_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/was4admin/nutriguide/controller/main.py", line 24, in <module>
    from .routes import services_router, prediction_router
  File "/home/was4admin/nutriguide/controller/routes/__init__.py", line 17, in <module>
    from ._prediction import prediction_router
  File "/home/was4admin/nutriguide/controller/routes/_prediction.py", line 26, in <module>
    from utils.configuration_utils import ControllerConfig, ContentGenerationConfig, NodeServerConfig, ContentSearchConfig
ImportError: cannot import name 'ContentGenerationConfig' from 'utils.configuration_utils' (/home/was4admin/nutriguide/utils/configuration_utils.py)
[2024-10-08 09:22:28 +0530] [49263] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 09:24:31 +0530] [49343] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 09:28:54 +0530] [49404] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 09:31:41 +0530] [49466] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 09:35:45 +0530] [49524] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 09:37:40 +0530] [49574] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 09:38:55 +0530] [49633] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 09:42:50 +0530] [49699] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 09:51:19 +0530] [49816] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 09:53:46 +0530] [49879] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 10:48:57 +0530] [50278] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 10:51:43 +0530] [50333] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 11:27:20 +0530] [50553] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 11:51:07 +0530] [50683] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 12:23:09 +0530] [52750] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 12:29:45 +0530] [52959] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 12:41:50 +0530] [53042] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 14:19:41 +0530] [53480] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 14:21:49 +0530] [53536] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 15:51:50 +0530] [54142] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 15:54:06 +0530] [54194] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 15:59:35 +0530] [54262] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 16:14:36 +0530] [54397] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
Traceback (most recent call last):
  File "/home/was4admin/.local/bin/hypercorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/__main__.py", line 304, in main
    return run(config)
           ^^^^^^^^^^^
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/run.py", line 39, in run
    sockets = config.create_sockets()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/config.py", line 200, in create_sockets
    secure_sockets = self._create_sockets(self.bind)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/config.py", line 269, in _create_sockets
    sock.bind(binding)
OSError: [Errno 98] Address already in use
[2024-10-08 16:23:23 +0530] [54485] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 17:17:43 +0530] [54952] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-08 17:19:23 +0530] [55015] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
Traceback (most recent call last):
  File "/home/was4admin/.local/bin/hypercorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/__main__.py", line 304, in main
    return run(config)
           ^^^^^^^^^^^
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/run.py", line 39, in run
    sockets = config.create_sockets()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/config.py", line 200, in create_sockets
    secure_sockets = self._create_sockets(self.bind)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/was4admin/.local/lib/python3.11/site-packages/hypercorn/config.py", line 269, in _create_sockets
    sock.bind(binding)
OSError: [Errno 98] Address already in use
[2024-10-08 17:32:49 +0530] [55200] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-10 10:24:00 +0530] [68356] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-10 10:26:45 +0530] [68414] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-10 12:05:24 +0530] [69113] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-10 12:13:27 +0530] [69192] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-10 12:16:01 +0530] [70134] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-10 12:18:22 +0530] [71176] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-10 12:35:55 +0530] [71471] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-10 12:38:35 +0530] [71562] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-10 14:29:28 +0530] [72253] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
[2024-10-14 09:50:47 +0530] [143919] [INFO] Running on https://10.81.32.201:7050 (CTRL + C to quit)
